### ISSUE TITLE
Add support for disp-quote

### ISSUE THREAD

**Issue by madileweb** [Vitaliy-1/JATSParser#13]
Hi, we're testing the plugin for one of our journals. We have cites with 'disp-quote' tag in our Jats XML that is not working.

Example:

<body>
	<sec sec-type="intro">
		<disp-quote>
			<p>
			...la pobreza afecta a adolescentes y jóvenes de una manera desproporcionada: en 2008, se estimaba que 35 millones de adolescentes de la región, de edades comprendidas entre los 13 y los 19 años, vivían por debajo del umbral de la pobreza. Casi 15 millones de adolescentes, de entre 10 y 18 años, vivían con menos de 1 dólar al día.
			</p>
		</disp-quote>
	</sec>
</body>

Thank you in advance
Diego

**Comment by Vitaliy-1** [comment]
The referenced commit should do the trick. It will be added in the next release.

**Comment by madileweb** [comment]
Thank you Vitaliy-1!
