### ISSUE TITLE
HTML: IDs for figures and tables are missing

### ISSUE THREAD

**Issue by Vitaliy-1** [Vitaliy-1/JATSParser#4]
Related to: https://forum.pkp.sfu.ca/t/jats-parser-v2-0-jats-xml-to-html-and-pdf-conversion/47704/58

**Comment by Nostrabramus** [comment]
Hi,
I this issue was fixed by this pull request:
f08e661#diff-5669f618eee6c5209c0a2883f036496b

**Comment by Vitaliy-1** [comment]
Yep, thanks :) Closing this one
