### ISSUE TITLE
Text nodes shouldn't be trimmed when converted to HTML

### ISSUE THREAD

**Issue by ericrav** [Vitaliy-1/JATSParser#6]
Sometimes writers/editors will accidentally make the space after an italicized word also italic.
When it's displayed on the page, those words will run together.

For example, with a JATS XML file like this:
```xml
<italic id="italic-9">Diplomacy </italic>reimagined ...
```
The space between the two words is included in the `<italic>`, but the html generated looks like this:
```html
<i>Diplomacy</i>
reimagined
```

Resulting in:
<img width="172" alt="Screen Shot 2019-06-21 at 6 48 56 PM" src="https://user-images.githubusercontent.com/3066943/59954904-427b0400-9455-11e9-8bef-f802ed0fad44.png">

I think it's because of the `trim` on this line https://github.com/Vitaliy-1/JATSParser/blob/master/src/JATSParser/HTML/Text.php#L71

**Comment by Vitaliy-1** [comment]
Hi @ericrav,

Sorry for the late response, does the problem appear if use master branch?

**Comment by ericrav** [comment]
I'm trying to test it, but I'm still on the version of JATSParserPlugin from before this submodule was created. I tried updating with the `.tar.gz` through OJS, but it says "The uploaded plugin archive does not contain a folder that corresponds to the plugin name." And when I tried unpacking the plugin directly into `plugins/generic`, nothing shows on the article page.

**Comment by Vitaliy-1** [comment]
Hi @ericrav,

Is this problem still relevant?
