### ISSUE TITLE
Anchor tags

### ISSUE THREAD

**Issue by ohilbig01** [Vitaliy-1/JATSParser#8]
Hi Vitaly, 
I think you forgot the anchor tags to jump to the figures.
In "./JATSParser/src/JATSParser/HTML/Figure.php", this works for me:

```
...        
	public function setContent(JATSFigure $jatsFigure) {

+               // anchor tags
+               $aNode = $this->ownerDocument->createElement("a");
+               $aNode->setAttribute("name", $jatsFigure->getId());
+               $this->appendChild($aNode);

...
```

Regards
Olaf

**Comment by Vitaliy-1** [comment]
Hi @ohilbig01,

Thanks! And I think the same applies and for tables too...

**Comment by Nostrabramus** [comment]
Hi,
I this issue was fixed by this pull request:
https://github.com/Vitaliy-1/JATSParser/commit/f08e661a605b8a273fa5bffb8dcfc06dfb8bcf22#diff-5669f618eee6c5209c0a2883f036496b

**Comment by Vitaliy-1** [comment]
Thanks. Closing.
